# Generated by Django 5.2.1 on 2025-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
